# fly.toml app configuration file generated for polygon-auto-annotate-tool on 2023-06-02T20:54:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polygon-auto-annotate-tool"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
